"""Progression Webnovel Kernel public contracts."""

from novel_authoring.progression.adapters import (
    BUILTIN_GENRE_ADAPTERS,
    compile_genre_adapters,
    effective_genre_contract,
)
from novel_authoring.progression.derived import compile_derived_adapter
from novel_authoring.progression.models import (
    AuthoringPreset,
    ContractStatus,
    DerivedAdapterSpec,
    EffectiveGenreContract,
    ExperiencePriority,
    ExplanationStyle,
    GenreAdapter,
    GenreAdapterKind,
    GenreContract,
    GenrePromise,
    GenrePromiseStrength,
    PayoffChannel,
    PrimaryFamily,
    ProgressionDeltaType,
    ProgressionSubject,
    ProgressionTopology,
    ReaderExperience,
    ReaderExperienceContract,
    RuntimeGenreCapabilities,
    SerialForm,
    SettingSkin,
    StoryProfile,
)
from novel_authoring.progression.presets import (
    BUILTIN_STORY_PROFILES,
    compile_story_profile,
)

__all__ = [
    "AuthoringPreset",
    "BUILTIN_STORY_PROFILES",
    "BUILTIN_GENRE_ADAPTERS",
    "ContractStatus",
    "DerivedAdapterSpec",
    "EffectiveGenreContract",
    "ExperiencePriority",
    "ExplanationStyle",
    "GenreAdapter",
    "GenreAdapterKind",
    "GenreContract",
    "GenrePromise",
    "GenrePromiseStrength",
    "PayoffChannel",
    "ProgressionDeltaType",
    "ProgressionSubject",
    "ProgressionTopology",
    "PrimaryFamily",
    "ReaderExperience",
    "ReaderExperienceContract",
    "RuntimeGenreCapabilities",
    "SerialForm",
    "SettingSkin",
    "StoryProfile",
    "compile_story_profile",
    "compile_genre_adapters",
    "compile_derived_adapter",
    "effective_genre_contract",
]
